#!/usr/bin/env python3
"""Write gamedata/sigsegv/windows.txt from matchfuncs.py's matches.

Every `sym` entry in gamedata/sigsegv whose symbol was matched in server.dll
becomes a `fixed` entry at the matched address, under the same name. The
extension loads this file before the others on Windows, and the first entry
registered under a name is the one that counts, so these stand in for the
Linux symbol lookups one for one.

`fixed` is tied to a server version, which is what it should be: the matches
are only true for the build they were made against.

    emitgamedata.py matches.json SERVER_VERSION [datamaps.json] > gamedata/sigsegv/windows.txt

tools/winport/overrides.json holds addresses checked by hand, keyed by Linux
symbol, and wins over matches.json.
"""

import glob
import re
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import classify  # noqa: E402

root = Path(__file__).resolve().parents[2]
matches = json.load(open(sys.argv[1]))
version = sys.argv[2]

# Addresses resolved by hand take precedence over anything matched, and say why.
# An override with its own "name" is an address the Linux gamedata does not
# have, usually because Windows needs a different function; "lib" defaults to
# server.
overrides = json.load(open(Path(__file__).parent / "overrides.json"))
for sym, entry in overrides.items():
    matches[sym] = {"rva": int(entry["rva"], 16), "via": "verified: " + entry["why"]}
extra = [(e["name"], {"type": "sym", "sym": s, "lib": e.get("lib", "server")}) for s, e in overrides.items() if "name" in e]

found = []
for path in sorted(glob.glob(str(root / "gamedata/sigsegv/*.txt"))):
    if path.endswith("windows.txt"):
        continue
    classify.walk_addrs(classify.parse(open(path).read()), found)

# classify.py's parser loses entries in some addrs_group blocks. Read those
# blocks directly as well: a [common] block with type and lib, then one
# "name" "symbol" line per address, up to the block's closing brace.
known = {name for name, _ in found}
for path in sorted(glob.glob(str(root / "gamedata/sigsegv/*.txt"))):
    if path.endswith("windows.txt"):
        continue
    lines = open(path).read().split("\n")
    i = 0
    while i < len(lines):
        if lines[i].strip() != '"addrs_group"':
            i += 1
            continue
        depth, common, i = 0, {}, i + 1
        while i < len(lines):
            line = lines[i].split("//")[0].strip()
            depth += line.count("{") - line.count("}")
            kv = re.match(r'^(type|lib)\s+"([^"]*)"$', line)
            if kv:
                common[kv.group(1)] = kv.group(2)
            pair = re.match(r'^"([^"]+)"\s+"([^"]+)"$', line)
            if pair and depth == 1 and pair.group(1) not in known:
                found.append((pair.group(1), {"type": common.get("type"), "lib": common.get("lib", "server"), "sym": pair.group(2)}))
                known.add(pair.group(1))
            if depth == 0 and "}" in line:
                break
            i += 1

out = [
    "// Generated by tools/winport/emitgamedata.py. Do not hand-edit.",
    f"// Addresses in server.dll for ServerVersion {version}, matched from server_srv.so.",
    "",
    '"Games"', "{", '\t"#default"', "\t{", '\t\t"#supported"', "\t\t{", '\t\t\tengine "tf2"', "\t\t}", "",
    '\t\t"sigsegv"', "\t\t{", '\t\t\t"addrs"', "\t\t\t{",
]
count = 0
# datamaps.py resolves each class's datamap statically; the runtime scan that
# finds them on Linux comes back empty on Windows.
if len(sys.argv) > 3:
    for class_name, entry in json.load(open(sys.argv[3])).items():
        matches[entry["sym"]] = {"rva": entry["rva"], "via": "datamaps.py: the datamap whose +8 names the class and that a GetDataDescMap returns"}
        found.append((class_name + "::m_DataMap", {"type": "sym", "sym": entry["sym"], "lib": "server"}))

found_names = {name for name, _ in found}
for name, entry in found + [x for x in extra if x[0] not in found_names]:
    lib = entry.get("lib", "server")
    if entry.get("type") != "sym" or (lib != "server" and "verified" not in matches.get(entry.get("sym"), {}).get("via", "")):
        continue
    match = matches.get(entry.get("sym"))
    if match is None and name.startswith("DT_") and name.endswith("::g_SendTable"):
        out += [
            f'\t\t\t\t"{name}"', "\t\t\t\t{",
            '\t\t\t\t\ttype  "sendtable"',
            f'\t\t\t\t\ttable "{name[:-len("::g_SendTable")]}"',
            "\t\t\t\t}",
        ]
        count += 1
        continue
    if match is None:
        continue
    # Structural matches go in only with field-offset evidence behind them: a
    # missing address fails its link out loud, a wrong one runs the wrong code.
    if match["via"] in ("call", "consensus", "table") and (match.get("fields") or 0) < 0.3:
        continue
    out += [
        f'\t\t\t\t"{name}"', "\t\t\t\t{",
        '\t\t\t\t\ttype  "fixed"',
        f'\t\t\t\t\tsym   "{entry["sym"]}"',
        f'\t\t\t\t\taddr  "0x{match["rva"]:x}"',
        f'\t\t\t\t\tbuild "{version}"',
        f'\t\t\t\t\tlib   "{lib}"',
        f'\t\t\t\t\t// {match["via"]}',
        "\t\t\t\t}",
    ]
    count += 1
out += ["\t\t\t}", "\t\t}", "\t}", "}", ""]
sys.stdout.write("\n".join(out))
print(f"{count} addresses", file=sys.stderr)
